version: '3.5'
services:

    agent_simulator:
        image: helyosframework/helyos_agent_slim_simulator:0.6.0
        build: ../
        tty: true
        volumes:
            - ./custom-geometry.json:/app/customization/geometry.json       # To modify reported geometry
            - ./ca_certificate.pem:/app/ca_certificate.pem                  # To verify rbmq server url
            # - ../src:/app                                                 # Uncomment to mount the source code into the container for developing

        environment:
            # Load environment from .env file

            # GENERAL VARIABLES
            - UUID=${UUID}
            - PATH_TRACKER=${PATH_TRACKER}
            - ASSIGNMENT_FORMAT=${ASSIGNMENT_FORMAT} 
            - NAME=${NAME}
            - X0=${X0}
            - Y0=${Y0}
            - ORIENTATION=${ORIENTATION}
            - VELOCITY=${VELOCITY}
            - VEHICLE_PARTS=${VEHICLE_PARTS}
            - YARD_UID=${YARD_UID}
            - UPDATE_RATE=${UPDATE_RATE}
            - CACERTIFICATE_FILENAME=${CACERTIFICATE_FILENAME}

            # RABBITMQ ENDPOINT SPEC
            - RBMQ_HOST=${RBMQ_HOST}
            - RBMQ_VHOST=${RBMQ_VHOST}
            - RBMQ_PORT=${RBMQ_PORT}

            # RABBITMQ PROTOCOL SPEC
            - ENABLE_SSL=${ENABLE_SSL}
            - PROTOCOL=${PROTOCOL}

            # RBMQ ACCOUNT
            # - RBMQ_USERNAME=${RBMQ_USERNAME}
            # - RBMQ_PASSWORD=${RBMQ_PASSWORD}
            # OR
            - REGISTRATION_TOKEN=${REGISTRATION_TOKEN}

        networks:
            - control-tower-net

networks:
    control-tower-net:
        name: control-tower-net
        external: true
